# https://github.com/actions/setup-java
# https://docs.github.com/en/actions/language-and-framework-guides/github-actions-for-java

name: graalpython_ci
on:
  pull_request:
  push:
jobs:
  graalpython_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - run: java -version
      - run: echo $JAVA_HOME
      - run: git clone https://github.com/graalvm/mx.git
      - run: cd graalpython ; ../mx/mx python-gate --tags style,fullbuild,python-unittest,python-unittest-jython
