# https://github.com/actions/setup-java
# https://docs.github.com/en/actions/language-and-framework-guides/github-actions-for-java

name: graalpython_ci
on:
  pull_request:
  push:
jobs:
  graalpython_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - run: java -version
      - run: git clone https://github.com/graalvm/mx.git
      - run: cd graalpython ; ../mx/mx build  # 7+ minutes
      - run: mx/mx python -c "print(42)"
      - run: mx/mx python --version  # Python 3.8.5 (Interpreted JVM Development Build)
      - run: mx/mx graalpython --version || true  # mx: unknown command 'graalpython'
      - run: graalpython --version || true  # graalpython: command not found
      - run: mx/mx python-svm || true  # 1 build tasks failed
      - run: graalpython --version || true  # graalpython: command not found
      - run: cd graalpython ; ../mx/mx python-svm || true
      - run: graalpython --version || true
      - run: mx/mx python-gate || true  # 22+ minutes --> java.lang.OutOfMemoryError: Java heap space
      - run: mx/mx benchmark --list
      - run: mx/mx benchmark meso --list
      - run: mx/mx benchmark meso:nbody3 || true  # Could not find a Java VM to default to.
